name: Update Tag on Commit

on:
  push:
    branches:
      - main
jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Git fetch tags
      run: |
        git fetch --prune --unshallow > /dev/null 2>&1
        git log --format=%B -n 1 $GITHUB_SHA

    - name: Determine Next Version
      id: version
      run: |
        chmod +x ./.github/workflows/getNextVersion.sh
        next_version=$(./.github/workflows/getNextVersion.sh)
        echo "Next version: $next_version"
        echo "::set-output name=version::$next_version"

    - name: Create or Update Tag
      run: |
        version=${{ steps.version.outputs.version }}
        tag="$version"
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git tag $tag $GITHUB_SHA -f
        git push origin $tag

    - name: Build Docker Image
      run: docker build -t szachmatyfrontendimage:${{ steps.version.outputs.version }} .

    - name:  
      run: docker save -o szachmatyfrontendimage${{ steps.version.outputs.version }}.tar szachmatyfrontendimage

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: v${{ steps.version.outputs.version }} 
        tag_name: ${{ steps.version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Add Docker image to Release
      uses: actions/upload-release-asset@v1 
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: szachmatyfrontendimage${{ steps.version.outputs.version }}.tar
        asset_name: szachmatyfrontendimagev${{ steps.version.outputs.version }}.tar
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}
